Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-dev' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libexpat1 libexpat1-dev libpython2.7 python2.7-dev
The following NEW packages will be installed:
  libexpat1-dev libpython2.7 python-dev python2.7-dev
The following packages will be upgraded:
  libexpat1
1 upgraded, 4 newly installed, 0 to remove and 4 not upgraded.
Need to get 24.4 MB of archives.
After this operation, 35.8 MB of additional disk space will be used.
Err http://debian.mur.at/debian/ wheezy/main libexpat1 amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
Err http://debian.mur.at/debian/ wheezy/main python-dev all 2.7.3-4+deb7u1
  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
Err http://security.debian.org/ wheezy/updates/main libexpat1 amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main libexpat1-dev amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main libpython2.7 amd64 2.7.3-6+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main python2.7-dev amd64 2.7.3-6+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/e/expat/libexpat1_2.1.0-1+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/e/expat/libexpat1-dev_2.1.0-1+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/p/python2.7/libpython2.7_2.7.3-6+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/p/python2.7/python2.7-dev_2.7.3-6+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://debian.mur.at/debian/pool/main/p/python-defaults/python-dev_2.7.3-4+deb7u1_all.deb  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: /Stage[main]/Circus::Install/Package[python-dev]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-dev' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libexpat1 libexpat1-dev libpython2.7 python2.7-dev
The following NEW packages will be installed:
  libexpat1-dev libpython2.7 python-dev python2.7-dev
The following packages will be upgraded:
  libexpat1
1 upgraded, 4 newly installed, 0 to remove and 4 not upgraded.
Need to get 24.4 MB of archives.
After this operation, 35.8 MB of additional disk space will be used.
Err http://debian.mur.at/debian/ wheezy/main libexpat1 amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
Err http://debian.mur.at/debian/ wheezy/main python-dev all 2.7.3-4+deb7u1
  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
Err http://security.debian.org/ wheezy/updates/main libexpat1 amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main libexpat1-dev amd64 2.1.0-1+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main libpython2.7 amd64 2.7.3-6+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Err http://security.debian.org/ wheezy/updates/main python2.7-dev amd64 2.7.3-6+deb7u2
  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/e/expat/libexpat1_2.1.0-1+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/e/expat/libexpat1-dev_2.1.0-1+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/p/python2.7/libpython2.7_2.7.3-6+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://security.debian.org/pool/updates/main/p/python2.7/python2.7-dev_2.7.3-6+deb7u2_amd64.deb  Cannot initiate the connection to security.debian.org:80 (2001:a78:5:1:216:35ff:fe7f:6ceb). - connect (101: Network is unreachable) [IP: 2001:a78:5:1:216:35ff:fe7f:6ceb 80]
Failed to fetch http://debian.mur.at/debian/pool/main/p/python-defaults/python-dev_2.7.3-4+deb7u1_all.deb  Cannot initiate the connection to debian.mur.at:80 (2a02:3e0::14:80). - connect (101: Network is unreachable) [IP: 2a02:3e0::14:80 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR 10:18:39.948 [citac-puppet]: Failed to apply 'Package[python-dev]'.
Notice: /Package[circus]: Dependency Package[python-dev] has failures: true
Warning: /Package[circus]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Install/File[/usr/bin/circusd]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Install/File[/usr/bin/circusd]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/etc/circus]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/etc/circus]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/etc/init.d/circus]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/etc/init.d/circus]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/var/log/circus]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/var/log/circus]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[pubsub_endpoint]/Ini_setting[pubsub_endpoint in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[pubsub_endpoint]/Ini_setting[pubsub_endpoint in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[endpoint]/Ini_setting[endpoint in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[endpoint]/Ini_setting[endpoint in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[include_dir]/Ini_setting[include_dir in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[include_dir]/Ini_setting[include_dir in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[use]/Ini_setting[use in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[use]/Ini_setting[use in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[check_delay]/Ini_setting[check_delay in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[check_delay]/Ini_setting[check_delay in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[stats_endpoint]/Ini_setting[stats_endpoint in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[stats_endpoint]/Ini_setting[stats_endpoint in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/etc/circus/conf.d]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/etc/circus/conf.d]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/File[/etc/logrotate.d/circus]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/File[/etc/logrotate.d/circus]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[max_retry]/Ini_setting[max_retry in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[max_retry]/Ini_setting[max_retry in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[logoutput]/Ini_setting[logoutput in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[logoutput]/Ini_setting[logoutput in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Configure/Circus::Setting[retry_in]/Ini_setting[retry_in in /etc/circus/circusd.ini]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Configure/Circus::Setting[retry_in]/Ini_setting[retry_in in /etc/circus/circusd.ini]: Skipping because of failed dependencies
Notice: /Stage[main]/Circus::Services/Service[circus]: Dependency Package[python-dev] has failures: true
Warning: /Stage[main]/Circus::Services/Service[circus]: Skipping because of failed dependencies
